### PR TITLE
Changed import statement to a workable one

### PR DESCRIPTION
**Pull request by npanpaliya**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
https://github.ibm.com/mldlppc/tracker/issues/11842

**Comment by pooyadavoodi** [comment]
@npanpaliya I tried your change and it didn't work for me:
How do you test it?

```
Traceback (most recent call last):
  File "image_classification.py", line 31, in <module>
    import official.resnet.ctl.ctl_imagenet_main
ModuleNotFoundError: No module named 'official.resnet.ctl'
```

**Comment by npanpaliya** [comment]
We test this script on IBM's Power systems with WML-CE packages that includes whole family of tensorflow, tensorrt, models, etc. I did following steps -

1. I cloned models source code ```https://github.com/tensorflow/models``` master branch and tensorrt source code from ```https://github.com/tensorflow/tensorrt/``` master branch. 
2. And then set the PYTHONPATH to point to slim directory from models and models root directory.
3. Installed tensorflow
3. Ran the image-classification script from tensorrt/tftrt/examples/image-classification/image_classification.py.

**Comment by npanpaliya** [comment]
The latest models source code has https://github.com/tensorflow/models/blob/master/official/resnet/ctl/ctl_imagenet_main.py, so the import change I did should have worked for you if you clone master models code.

**Comment by pooyadavoodi** [comment]
@npanpaliya Thanks for the PR

**Pull request merged**
