### PR TITLE
Update TFTRT scripts to work with TRT 8.0

### PR DESCRIPTION
**Pull request by jhalakpatel**

### CODE REVIEW

**Comment by jhalakpatel** [comment]
@googlebot I signed it!

**Comment by DEKHTIARJonathan** [comment]
@jhalakp-nvidia can you squash your commit using only your NV email ? Seems like your two users confuse the Google CLA Bot

**Comment by jhalakpatel** [comment]
@googlebot I consent.

**Comment by jhalakp-nvidia** [comment]
@googlebot I consent.

**Comment by DEKHTIARJonathan** [comment]
Closing. Already merged in fe7d53f91e4863542fee0baf48d1ae371b6b8ed0

**Pull request closed without merging**
